export const POST_PROTEST_ERROR = 'POST_PROTEST_ERROR'
export const POST_PROTEST_SUCCESS = 'POST_SUCCESS_PROTEST'

export const GET_PROTEST_SUCCESS = 'GET_PROTEST_SUCCESS'
export const GET_PROTEST_ERROR = 'GET_PROTEST_ERROR'

export const LIKE_SUCCESS = 'LIKE_SUCCESS'
export const LIKE_ERROR = 'LIKE_ERROR'

export const DISLIKE_SUCCESS = 'DISLIKE_SUCCESS'
export const DISLIKE_ERROR = 'DISLIKE_ERROR'
